FROM nginx:latest

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY ./index.html /usr/share/nginx/html

# COPY /etc/letsencrypt/live/k13c101.p.ssafy.io/fullchain.pem /etc/letsencrypt/live/k13c101.p.ssafy.io/fullchain.pem
# COPY /etc/letsencrypt/live/k13c101.p.ssafy.io/privkey.pem /etc/letsencrypt/live/k13c101.p.ssafy.io/privkey.pem