pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
                
        stage('Build FastAPI Docker Image') {
            steps {
                sh 'docker build -t fastapi-reborn .'
            }
        }

        stage('Run Docker Compose') {
            steps {
                dir('infra') {
                    sh 'docker compose down'
                    
                    sh 'docker compose up -d --build'
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}