FROM eclipse-mosquitto:2.0

COPY ./config /mosquitto/config
COPY ./data /mosquitto/data
COPY ./log /mosquitto/log

COPY /etc/letsencrypt/live/k13c101.p.ssafy.io /etc/letsencrypt/live/k13c101.p.ssafy.io